version = 0.1
[default.deploy.parameters]
stack_name = "strava-plugin-oauth-proxy"
resolve_s3 = true
s3_prefix = "strava-plugin-oauth-proxy"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "StageName=\"prod\""
image_repositories = []
