version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "strava-plugin-oauth-proxy"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_prefix = "strava-plugin-oauth-proxy"
region = "us-east-1"
disable_rollback = true
parameter_overrides = "StageName=\"prod\""
image_repositories = []
[default.build]
[default.build.parameters]
use_container = true