name: Feature Branch CI

on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint
        
      - name: Run tests
        run: npm test
        
      - name: Build extension (dev mode)
        run: npm run build:dev
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: extension-dev-build
          path: dist/
          retention-days: 7